name: CI

on: [push,pull_request]

jobs:
  build:

    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [macos-latest, ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        rustup component add rustfmt
        rustup component add clippy
        cargo build --verbose
    - name: Fmt check
      run: cargo fmt --all -- --check
    - name: Lint
      run: cargo clippy -- -D warnings
    - name: Run tests
      run: |
        cargo run -- -d t/default.json
        cargo run -- -o t/default.satyh -c t/default.json
        docker run --rm -v $(pwd):/satysfi amutake/satysfi:slim t/default.saty -o t/default.pdf
        cargo test --verbose
