name: CI

on: [push,pull_request]

jobs:
  build:

    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        satysfi-version: [slim]
    container:
      image: amutake/satysfi:${{ matrix.satysfi-version }}

    steps:
      - uses: actions/checkout@v2
      - name: Install stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: |
            cargo build --verbose
            cargo fmt --all -- --check
            cargo clippy -- -D warnings
            make test
            cargo test --verbose
